name: Build Code

on:
  workflow_call:

jobs:
  build-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21.x"]
    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5