name: Build Code

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node
    steps:
      - name: Download the Source Repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183666822:role/build-role-for-github
          aws-region: us-east-1
      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Read Version
        id: Release
        run: |
          VERSION=$(cat version.yml)
          echo ::set-output name=version::$VERSION
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: patts-private-ecr
          IMAGE_TAG: ${{ github.sha }}
          VERSION: ${{steps.Release.outputs.version}}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$VERSION .
          docker push "$REGISTRY/$REPOSITORY:$VERSION"
