name: CI

on:
  push:
    branches: [main]
jobs:
  build:
    uses: ./.github/workflows/build-node.yml

  unit-test:
    uses: ./.github/workflows/unit-test.yml

  dev-deploy:
    needs: [build, unit-test]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: dev
    secrets: inherit

  staging-deploy:
    needs: dev-deploy
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: staging
    secrets: inherit